# Generated by Django 4.2.3 on 2023-07-24 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0002_account_groups_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
