# Generated by Django 4.2.3 on 2023-07-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0005_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
